import os
import time
def informacion_personal(Primernombre,Segundonombre,Primerapellido,Segundoapellido,Edad,Rut,Telefono,Saldo):
    print("*******************************************************")
    punto="."
    print()
    print("Nombre completo:",Primernombre.upper(),Segundonombre.upper(),Primerapellido.upper(),Segundoapellido.upper())
    print("Edad:",Edad)
    print("Rut:",Rut[0:2]+punto+Rut[2:5]+punto+Rut[5:len(Rut)])
    print("Telefono: +"+Telefono)
    print("Saldo:",Saldo)
    print()
    print("*******************************************************")
def carga():
    punto="."
    carga=1
    os.system("cls")
    for i in range(0,2):
        while carga!=4:
            os.system("cls")
            print("*******************************************************")
            print()
            print("                  cargando"+(punto*carga))
            print()
            print("*******************************************************")
            time.sleep(1)
            carga=carga+1
        carga=1
    os.system("cls")
def correcion():
    print("*******************************************************")
    print()
    print("             ¿Es Correcta la informacion?")
    print()
    print("*******************************************************")
def credito(Primernombre,Segundonombre,Primerapellido,Segundoapellido,Edad,Rut,Telefono,Saldo,Monto):
    os.system("cls")
    print("**********************************************************************")
    print()  
    print("Nombre completo:",Primernombre.upper(),Segundonombre.upper(),Primerapellido.upper(),Segundoapellido.upper())
    print("Edad:",Edad)
    print("Rut:",Rut[0:2]+punto+Rut[2:5]+punto+Rut[5:len(Rut)])
    print("Telefono: +"+Telefono)
    print("Saldo:",Saldo)
    print("Monto solicitado:",Monto)
    #completar

print("*******************************************************")
print()
print("Bienvenido al servicio de contratacion de creditos ICI")
print()
print("*******************************************************")
time.sleep(8)
print()
os.system("cls")
print("**********************************************************************")
print()
print("Para poder contratar un credito, es necesario algunos datos personales")
print()
print("**********************************************************************")
time.sleep(8)
print()
primernombre=str(input("Ingrese su primer nombre:"))
segundonombre=str(input("ingrese su segundo nombre:"))
primerapellido=str(input("Ingrese su primer apellido:"))
segundoapellido=str(input("ingrese su segundo apellido:"))
edad=int(input("ingrese su edad:"))
rut=input("ingrese su rut (123456789-0):")
telefono=input("ingress su numero telefonico (***123456789):+")
saldo=int(input("ingrese su salario mensual:"))
carga()
informacion_personal(primernombre,segundonombre,primerapellido,segundoapellido,edad,rut,telefono,saldo)
correcion()
respuestacorrecion=int(input("Es correcto = 1 / Es Incorrecto = 2. Su respuesta es:"))
while respuestacorrecion!=1 and respuestacorrecion!=2:
    respuestacorrecion=int(input("Es correcto = 1 / Es Incorrecto = 2. Su respuesta es:"))
while respuestacorrecion==2:
    os.system("cls")
    print("**********************************************************************")
    print()
    primernombre=str(input("Ingrese su primer nombre:"))
    segundonombre=str(input("ingrese su segundo nombre:"))
    primerapellido=str(input("Ingrese su primer apellido:"))
    segundoapellido=str(input("ingrese su segundo apellido:"))
    edad=int(input("ingrese su edad:"))
    rut=input("ingrese su rut (123456789-0):")
    telefono=input("ingrese su numero telefonico (***123456789):+")
    saldo=int(input("ingrese su salario mensual:"))
    carga()
    informacion_personal(primernombre,segundonombre,primerapellido,segundoapellido,edad,rut,telefono,saldo)
    correcion()
    respuestacorrecion=int(input("Es correcto = 1 / Es Incorrecto = 2. Su respuesta es:"))
    while respuestacorrecion!=1 and respuestacorrecion!=2:
        respuestacorrecion=int(input("Es correcto = 1 / Es Incorrecto = 2. Su respuesta es:"))
os.system("cls")
print("************************************************************************************")
print()
print("        Ahora necesitamos saber si Usted tiene algun otro credito activo")
print()
print("************************************************************************************")
print()
print("                         ¿Tiene algun Credito activo?")
print()
print("************************************************************************************")
respuestacreditoactivo=int(input("Si tengo un credito activo (1) / No tengo un credito activo (2). Su resuesta es:"))
while respuestacreditoactivo!=1 and respuestacreditoactivo!=2:
    os.system("cls")
    print("************************************************************************************")
    print()
    print("        Ahora necesitamos saber si Usted tiene algun otro credito activo")
    print()
    print("************************************************************************************")
    print()
    print("                         ¿Tiene algun Credito activo?")
    print()
    print("************************************************************************************")
    respuestacreditoactivo=int(input("Si tengo un credito activo (1) / No tengo un credito activo (2). Su resuesta es:"))
if respuestacreditoactivo==1:
    asudfhasdh# completar
else:
    os.system("cls")
    print("*****************************************************************")
    print()
    print("Muy bien, ahora podemos empezar con la contratacion del creditos")
    print()
    print("*****************************************************************")
    time.sleep(5)
    os.system("cls")
    print("*****************************************************************")
    print()
    print("        Ahora se necesita que complete otros datos")
    print()
    print("*****************************************************************")
    time.sleep(4)
    os.system("cls")
    print("*****************************************************************")
    credito=int(input("Ingrese el Monoto que desea solicitar:"))
    meses=int(input("En cuantos Meses desea que sea el plaso (12-60):"))
    if credito<=-1:
        while credito<=-1:
            credito=int(input("Ingrese el Monoto que desea solicitar:"))
    if meses<12 and meses>60:
        while meses<12 and meses>60:
            meses=int(input("En cuantos Meses desea que sea el plaso (12-60):"))
    os.system("cls")
    carga()
    #completar
